---
apiVersion: v1
kind: Pod
metadata:
  name: metric-exporter-demo
#  namespace: metric-test
  labels:
    app: metric-exporter-demo
  annotations:
      sidecar.opentelemetry.io/inject: "true"
spec:
  containers:
    - name: exporter
      image: metric-exporter-demo
      imagePullPolicy: IfNotPresent
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
          name: http
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: metric-exporter-demo
# #  namespace: metric-test
#   labels:
#     app: metric-exporter-demo
# spec:
#   selector:
#     app: metric-exporter-demo
#   ports:
#     - port: 8080
#       targetPort: 8080
#       name: http
# 
# ---
# apiVersion: monitoring.coreos.com/v1
# kind: ServiceMonitor
# metadata:
#   labels:
#     app: metric-exporter-demo
#   name: metric-exporter-demo
# #  namespace: metric-test
# spec:
#   endpoints:
#   - honorLabels: true
#     path: /metrics
#     port: http
#     scheme: http
#     scrapeTimeout: 30s
#   jobLabel: metric-exporter-demo
#   namespaceSelector:
#     matchNames:
#     - metric-test
#   selector:
#      matchLabels:
#        app: metric-exporter-demo
# 
