apiVersion: v1
kind: Pod
metadata:
  name: metric-exporter-demo
  namespace: metric-test
  labels:
    app: metric-exporter-demo
spec:
  containers:
    - name: exporter
      image: metric-exporter-demo
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 8080
